-- =====================================================
-- Oforson Proxies — QA / sandbox seed data
-- Run this in the Supabase SQL editor AFTER 001..005
-- Idempotent: safe to run repeatedly. Wipes only its own QA rows.
--
-- Creates 6 fake users, residential + datacenter subscriptions,
-- active proxy sessions, 30 days of bandwidth_usage history,
-- payment_history, api_keys, support tickets, and one user
-- who has BLOWN PAST their bandwidth cap so you can test the
-- soft-lock + upgrade flow.
--
-- Login credentials (password is the same for every QA user):
--   password:  TestPass!2026
--
--   admin@qa.oforson.test          (admin, $0 plan)
--   pro.res@qa.oforson.test        (Pro, rotating residential, ~57% used)
--   biz.static@qa.oforson.test     (Business, static residential, ~30% used)
--   ent.dc@qa.oforson.test         (Enterprise, datacenter, ~20% used)
--   trial.dc@qa.oforson.test       (Trialing, datacenter, ~5% used)
--   capped@qa.oforson.test         (Pro, rotating residential, OVER LIMIT)
-- =====================================================

begin;

-- ---------------------------------------------------------
-- 0. Clean previous QA data (idempotent re-runs)
-- ---------------------------------------------------------
do $$
declare
  qa_ids uuid[];
begin
  select array_agg(id) into qa_ids
  from auth.users
  where email like '%@qa.oforson.test';

  if qa_ids is not null then
    delete from public.bandwidth_usage     where user_id = any(qa_ids);
    delete from public.proxy_sessions      where user_id = any(qa_ids);
    delete from public.proxy_orders        where user_id = any(qa_ids);
    delete from public.subscriptions       where user_id = any(qa_ids);
    delete from public.payment_history     where user_id = any(qa_ids);
    delete from public.api_keys            where user_id = any(qa_ids);
    delete from public.support_tickets     where user_id = any(qa_ids);
    delete from public.notifications       where user_id = any(qa_ids);
    delete from public.admin_audit_logs    where admin_user_id = any(qa_ids) or affected_user_id = any(qa_ids);
    delete from public.profiles            where id = any(qa_ids);
    delete from auth.identities            where user_id = any(qa_ids);
    delete from auth.users                 where id = any(qa_ids);
  end if;
end$$;

-- ---------------------------------------------------------
-- 1. Create auth users + identities
--    Uses Supabase's internal columns. Password hash is bcrypt
--    of "TestPass!2026" generated by pgcrypto crypt().
-- ---------------------------------------------------------
do $$
declare
  pw_hash text := crypt('TestPass!2026', gen_salt('bf'));
  users jsonb := jsonb_build_array(
    jsonb_build_object('id', '11111111-1111-1111-1111-111111111111', 'email', 'admin@qa.oforson.test',      'username', 'qa_admin',       'is_admin', true),
    jsonb_build_object('id', '22222222-2222-2222-2222-222222222222', 'email', 'pro.res@qa.oforson.test',    'username', 'qa_pro_res',     'is_admin', false),
    jsonb_build_object('id', '33333333-3333-3333-3333-333333333333', 'email', 'biz.static@qa.oforson.test', 'username', 'qa_biz_static',  'is_admin', false),
    jsonb_build_object('id', '44444444-4444-4444-4444-444444444444', 'email', 'ent.dc@qa.oforson.test',     'username', 'qa_ent_dc',      'is_admin', false),
    jsonb_build_object('id', '55555555-5555-5555-5555-555555555555', 'email', 'trial.dc@qa.oforson.test',   'username', 'qa_trial_dc',    'is_admin', false),
    jsonb_build_object('id', '66666666-6666-6666-6666-666666666666', 'email', 'capped@qa.oforson.test',     'username', 'qa_capped',      'is_admin', false)
  );
  u jsonb;
begin
  for u in select * from jsonb_array_elements(users) loop
    insert into auth.users (
      instance_id, id, aud, role, email,
      encrypted_password, email_confirmed_at, raw_app_meta_data,
      raw_user_meta_data, created_at, updated_at,
      confirmation_token, recovery_token, email_change_token_new, email_change
    )
    values (
      '00000000-0000-0000-0000-000000000000',
      (u->>'id')::uuid,
      'authenticated', 'authenticated',
      u->>'email',
      pw_hash,
      now() - interval '30 days',
      jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')),
      jsonb_build_object('username', u->>'username'),
      now() - interval '30 days',
      now(),
      '', '', '', ''
    );

    insert into auth.identities (
      id, user_id, provider, provider_id, identity_data, last_sign_in_at, created_at, updated_at
    )
    values (
      gen_random_uuid(),
      (u->>'id')::uuid,
      'email',
      (u->>'id'),
      jsonb_build_object('sub', u->>'id', 'email', u->>'email', 'email_verified', true),
      now(), now(), now()
    );

    -- handle_new_user trigger should auto-insert profiles, but be defensive
    insert into public.profiles (id, email, username, is_admin, account_status, created_at, updated_at)
    values (
      (u->>'id')::uuid,
      u->>'email',
      u->>'username',
      (u->>'is_admin')::boolean,
      'active',
      now() - interval '30 days',
      now()
    )
    on conflict (id) do update
    set username      = excluded.username,
        is_admin      = excluded.is_admin,
        account_status= excluded.account_status;
  end loop;
end$$;

-- ---------------------------------------------------------
-- 2. Subscriptions (one per non-admin user)
--
-- IMPORTANT: handle_new_user() (see 005_fix_signup_trigger.sql) inserts
-- a default 'free' subscription for EVERY new auth.users row. Step 1
-- above triggered that for all six QA users, so each one currently has
-- a 'free' subscription. If we just append the real ones below, every
-- QA user ends up with two subscription rows and the dashboard's
-- "newest subscription wins" query becomes a coin flip — that's why
-- the dashboard previously rendered identically for every user.
--
-- Wipe the trigger-created rows for QA users first, then insert the
-- real ones cleanly.
-- ---------------------------------------------------------
delete from public.subscriptions
 where user_id in (
   '11111111-1111-1111-1111-111111111111',
   '22222222-2222-2222-2222-222222222222',
   '33333333-3333-3333-3333-333333333333',
   '44444444-4444-4444-4444-444444444444',
   '55555555-5555-5555-5555-555555555555',
   '66666666-6666-6666-6666-666666666666'
 );

insert into public.subscriptions
  (user_id, plan, status, bandwidth_gb, bandwidth_used_gb, proxy_type,
   current_period_start, current_period_end, stripe_subscription_id)
values
  ('22222222-2222-2222-2222-222222222222', 'pro',        'active',    750,   428.6, 'rotating_residential',
   now() - interval '17 days', now() + interval '13 days', 'sub_qa_pro_res'),
  ('33333333-3333-3333-3333-333333333333', 'business',   'active',   2000,   612.4, 'static_residential',
   now() - interval '9 days',  now() + interval '21 days', 'sub_qa_biz_static'),
  ('44444444-4444-4444-4444-444444444444', 'enterprise', 'active',  10000,  1980.2, 'datacenter',
   now() - interval '12 days', now() + interval '18 days', 'sub_qa_ent_dc'),
  ('55555555-5555-5555-5555-555555555555', 'starter',    'trialing',  100,     5.1, 'datacenter',
   now() - interval '4 days',  now() + interval '10 days', null),
  -- CAPPED user: bandwidth_used_gb > bandwidth_gb. UI should flip into "limit hit" state.
  ('66666666-6666-6666-6666-666666666666', 'pro',        'past_due',  750,   812.7, 'rotating_residential',
   now() - interval '28 days', now() + interval '2 days',  'sub_qa_capped');

-- ---------------------------------------------------------
-- 3. Active proxy sessions
-- ---------------------------------------------------------
insert into public.proxy_sessions
  (user_id, proxy_type, country_code, ip_address, port, username, password, bandwidth_used, is_active, started_at)
values
  -- pro.res — 3 active rotating sessions
  ('22222222-2222-2222-2222-222222222222', 'rotating_residential', 'US', '184.22.45.10'::inet, 8000, 'qa_pro_res-rot1', 'p_rot1',  4_823_000_000, true,  now() - interval '2 hours'),
  ('22222222-2222-2222-2222-222222222222', 'rotating_residential', 'GB', '88.12.4.99'::inet,   8001, 'qa_pro_res-rot2', 'p_rot2',  1_120_000_000, true,  now() - interval '40 minutes'),
  ('22222222-2222-2222-2222-222222222222', 'rotating_residential', 'DE', '46.101.5.22'::inet,  8002, 'qa_pro_res-rot3', 'p_rot3',     50_000_000, true,  now() - interval '5 minutes'),

  -- biz.static — 2 static residential
  ('33333333-3333-3333-3333-333333333333', 'static_residential', 'US', '23.95.221.4'::inet,  9000, 'qa_biz_static-s1', 'p_s1',   8_400_000_000, true,  now() - interval '6 days'),
  ('33333333-3333-3333-3333-333333333333', 'static_residential', 'CA', '142.44.180.6'::inet, 9001, 'qa_biz_static-s2', 'p_s2',   3_100_000_000, true,  now() - interval '6 days'),

  -- ent.dc — 4 datacenter
  ('44444444-4444-4444-4444-444444444444', 'datacenter', 'US', '45.32.10.1'::inet,  10000, 'qa_ent_dc-d1', 'p_d1',  120_000_000_000, true,  now() - interval '12 days'),
  ('44444444-4444-4444-4444-444444444444', 'datacenter', 'US', '45.32.10.2'::inet,  10001, 'qa_ent_dc-d2', 'p_d2',  118_000_000_000, true,  now() - interval '12 days'),
  ('44444444-4444-4444-4444-444444444444', 'datacenter', 'NL', '95.179.10.3'::inet, 10002, 'qa_ent_dc-d3', 'p_d3',   90_000_000_000, true,  now() - interval '10 days'),
  ('44444444-4444-4444-4444-444444444444', 'datacenter', 'SG', '139.180.10.4'::inet,10003, 'qa_ent_dc-d4', 'p_d4',   72_000_000_000, true,  now() - interval '8 days'),

  -- trial.dc — 1 datacenter (trial)
  ('55555555-5555-5555-5555-555555555555', 'datacenter', 'US', '45.77.50.1'::inet, 10100, 'qa_trial_dc-d1', 'p_t1',  5_400_000_000, true,  now() - interval '3 days'),

  -- capped — 1 still active (so the soft-lock UI has something to throttle/disable)
  ('66666666-6666-6666-6666-666666666666', 'rotating_residential', 'US', '184.22.99.99'::inet, 8500, 'qa_capped-rot1', 'p_c1', 30_000_000_000, true, now() - interval '20 days'),

  -- A handful of ended sessions for the "history" view
  ('22222222-2222-2222-2222-222222222222', 'rotating_residential', 'JP', '203.0.113.7'::inet, 8003, 'qa_pro_res-old1', 'old1', 2_000_000_000, false, now() - interval '8 days'),
  ('33333333-3333-3333-3333-333333333333', 'static_residential',    'AU', '203.0.113.9'::inet, 9100, 'qa_biz_static-old1','old1', 600_000_000, false, now() - interval '5 days');

update public.proxy_sessions
   set ended_at = started_at + interval '1 day'
 where is_active = false and ended_at is null;

-- ---------------------------------------------------------
-- 4. Bandwidth usage (30 days of hourly-ish rollups)
--    The dashboard groups by day, so per-day buckets are enough.
-- ---------------------------------------------------------
do $$
declare
  d int;
  uid uuid;
  ptype proxy_type;
  base bigint;
  jitter bigint;
  users record;
begin
  for users in
    select user_id, proxy_type from public.subscriptions
  loop
    uid := users.user_id;
    ptype := users.proxy_type;
    -- datacenter users move way more traffic than residential
    base := case
      when ptype = 'datacenter' then 60_000_000_000   -- 60 GB / day
      when ptype = 'static_residential' then 18_000_000_000
      else 12_000_000_000
    end;

    for d in 0..29 loop
      jitter := (random() * base * 0.4)::bigint - (base * 0.2)::bigint;
      insert into public.bandwidth_usage (user_id, bytes_used, proxy_type, recorded_at)
      values (
        uid,
        greatest(base + jitter, 100_000_000),
        ptype,
        date_trunc('day', now()) - (d || ' days')::interval + (floor(random()*23) || ' hours')::interval
      );
    end loop;
  end loop;

  -- Push the capped user into clear overage territory today
  insert into public.bandwidth_usage (user_id, bytes_used, proxy_type, recorded_at)
  values (
    '66666666-6666-6666-6666-666666666666',
    80_000_000_000,  -- +80 GB spike today
    'rotating_residential',
    now() - interval '15 minutes'
  );
end$$;

-- ---------------------------------------------------------
-- 5. Payment history (Stripe-style)
-- ---------------------------------------------------------
insert into public.payment_history
  (user_id, amount, currency, status, invoice_url, description, stripe_invoice_id, created_at)
values
  ('22222222-2222-2222-2222-222222222222',  99.00, 'usd', 'succeeded', 'https://stripe.test/invoice/qa_pro_05','Pro plan — May 2026',         'in_qa_pro_05', now() - interval '17 days'),
  ('22222222-2222-2222-2222-222222222222',  99.00, 'usd', 'succeeded', 'https://stripe.test/invoice/qa_pro_04','Pro plan — Apr 2026',         'in_qa_pro_04', now() - interval '47 days'),
  ('33333333-3333-3333-3333-333333333333', 299.00, 'usd', 'succeeded', 'https://stripe.test/invoice/qa_biz_05','Business plan — May 2026',    'in_qa_biz_05', now() - interval '9 days'),
  ('44444444-4444-4444-4444-444444444444', 999.00, 'usd', 'succeeded', 'https://stripe.test/invoice/qa_ent_05','Enterprise plan — May 2026',  'in_qa_ent_05', now() - interval '12 days'),
  ('44444444-4444-4444-4444-444444444444', 999.00, 'usd', 'succeeded', 'https://stripe.test/invoice/qa_ent_04','Enterprise plan — Apr 2026',  'in_qa_ent_04', now() - interval '42 days'),
  ('66666666-6666-6666-6666-666666666666',  99.00, 'usd', 'failed',    null,                                   'Pro plan — May 2026 (retry)','in_qa_capped_05_fail', now() - interval '2 days'),
  ('66666666-6666-6666-6666-666666666666',  99.00, 'usd', 'succeeded', 'https://stripe.test/invoice/qa_capped_04','Pro plan — Apr 2026',     'in_qa_capped_04', now() - interval '28 days');

-- ---------------------------------------------------------
-- 6. API keys (hashes are fake — never used to authenticate)
-- ---------------------------------------------------------
insert into public.api_keys (user_id, name, key_hash, key_prefix, last_used_at, created_at)
values
  ('22222222-2222-2222-2222-222222222222', 'prod-scraper',   encode(digest('qa-fake-pro-key',    'sha256'),'hex'), 'ofo_live_aB12', now() - interval '1 hour',  now() - interval '14 days'),
  ('33333333-3333-3333-3333-333333333333', 'crawler-east',   encode(digest('qa-fake-biz-key',    'sha256'),'hex'), 'ofo_live_xY99', now() - interval '20 minutes', now() - interval '8 days'),
  ('44444444-4444-4444-4444-444444444444', 'data-pipeline',  encode(digest('qa-fake-ent-key',    'sha256'),'hex'), 'ofo_live_z7Q3', now() - interval '5 minutes',  now() - interval '11 days');

-- ---------------------------------------------------------
-- 7. Support tickets
-- ---------------------------------------------------------
insert into public.support_tickets (user_id, subject, body, status, priority)
values
  ('66666666-6666-6666-6666-666666666666', 'Hit my bandwidth cap', 'Need an emergency top-up before my crawler dies.', 'open',     'urgent'),
  ('33333333-3333-3333-3333-333333333333', 'Sticky session lengths', 'Can we raise the static session TTL past 30 min?', 'pending', 'normal'),
  ('22222222-2222-2222-2222-222222222222', 'Question about API limits', 'What is the rate limit on /api/proxies/list?', 'resolved','low');

-- ---------------------------------------------------------
-- 8. Notifications
-- ---------------------------------------------------------
insert into public.notifications (user_id, title, body, read, type)
values
  ('66666666-6666-6666-6666-666666666666', 'Bandwidth limit reached', 'You have used 108% of your monthly bandwidth. Upgrade to keep proxies active.', false, 'warning'),
  ('22222222-2222-2222-2222-222222222222', 'New rotating pool: LATAM', 'Brazil + Mexico IPs added to your rotating pool.', false, 'info'),
  ('44444444-4444-4444-4444-444444444444', 'Invoice paid', 'Your $999 enterprise invoice was paid successfully.', true, 'success');

commit;

-- Smoke check
select
  p.email,
  p.is_admin,
  s.plan,
  s.proxy_type,
  s.status,
  s.bandwidth_used_gb || ' / ' || s.bandwidth_gb || ' GB' as bandwidth,
  round((s.bandwidth_used_gb / nullif(s.bandwidth_gb,0)) * 100, 1) as pct_used
from public.profiles p
left join public.subscriptions s on s.user_id = p.id
where p.email like '%@qa.oforson.test'
order by p.email;
